name       : python-six
version    : 1.9.0
release    : 2
source     :
    - https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz : e24052411fc4fbd1f672635537c3fc2330d9481b18c0317695b46259512c91d5
license    : custom
summary    : Six is a Python 2 and 3 compatibility library
description: |
    Six is a Python 2 and 3 compatibility library
builddeps  :
    - python3-devel
setup      : |
build      : |
    python3 setup.py build
install    : |
    python3 setup.py install --root=%installroot% --no-compile -O0
