name       : python-six
version    : 1.12.0
release    : 9
source     :
    - https://pypi.io/packages/source/s/six/six-1.12.0.tar.gz : d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73
license    : MIT
component  : programming.python
summary    : Six is a Python 2 and 3 compatibility library
description: |
    Six provides simple utilities for wrapping over differences between Python 2 and Python 3.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
    - python-setuptools
    - python-tkinter
    - python3-tkinter
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test py.test
#    %python3_test py.test3
