name       : python-six
version    : 1.16.0
release    : 15
source     :
    - https://pypi.io/packages/source/s/six/six-1.16.0.tar.gz : 1e61c37477a1626458e36f7b1d82aa5c9b094fa4802892072e49de9c60c4c926
license    : MIT
component  : programming.python
summary    : Six is a Python 2 and 3 compatibility library
description: |
    Six provides simple utilities for wrapping over differences between Python 2 and Python 3.
builddeps  :
    - pkgconfig(python3)
    - python2-pytest
    - python-pytest
    - python-setuptools
    - python-tkinter
    - python3-tkinter
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    #python_test py.test
    %python3_test py.test3
