name       : python-six
version    : 1.10.0
release    : 6
source     :
    - https://pypi.python.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz : 105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a
license    : MIT
component  : programming.python
summary    : Six is a Python 2 and 3 compatibility library
description: |
    Six is a Python 2 and 3 compatibility library
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
