name       : python-six
version    : 1.15.0
release    : 12
source     :
    - https://pypi.io/packages/source/s/six/six-1.15.0.tar.gz : 30639c035cdb23534cd4aa2dd52c3bf48f06e5f4a941509c8bafd8ce11080259
license    : MIT
component  : programming.python
summary    : Six is a Python 2 and 3 compatibility library
description: |
    Six provides simple utilities for wrapping over differences between Python 2 and Python 3.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
    - python-setuptools
    - python-tkinter
    - python3-tkinter
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test
    %python3_test py.test3
