name       : python-six
version    : 1.9.0
release    : 3
source     :
    - https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz : e24052411fc4fbd1f672635537c3fc2330d9481b18c0317695b46259512c91d5
license    : MIT
summary    : Six is a Python 2 and 3 compatibility library
description: |
    Six is a Python 2 and 3 compatibility library
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.4)
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
